### ISSUE TITLE
vvvvid does not work

### ISSUE THREAD

**Issue by lordmarte** [Robotex/KAADIVVVV#27]
vvvvid.js?v=1.0.7293:1 VVVVID Exception PlayerObject.playNext() Cannot read property 'playlistItem' of undefined TypeError: Cannot read property 'playlistItem' of undefined
    at startAdv (<anonymous>:19:13)
    at s.playItem (https://static.vvvvid.it/js/vvvvid.js?v=1.0.7293:1:112067)
    at s.playNext (https://static.vvvvid.it/js/vvvvid.js?v=1.0.7293:1:116346)
    at setPlayerWithPlaylist (https://static.vvvvid.it/js/vvvvid.js?v=1.0.7293:1:111584)
    at g (https://static.vvvvid.it/js/vvvvid.js?v=1.0.7293:1:450964)
    at s.initializePlayerWithPlaylist (https://static.vvvvid.it/js/vvvvid.js?v=1.0.7293:1:451045)
    at startPlayer (https://static.vvvvid.it/js/vvvvid.js?v=1.0.7293:1:435613)
    at success (https://static.vvvvid.it/js/vvvvid.js?v=1.0.7293:1:434541)
    at t.success (https://static.vvvvid.it/js/vvvvid_libs.js?v=1.0.6583:8:10435)
    at Object.c.success (https://static.vvvvid.it/js/vvvvid.js?v=1.0.7293:1:73243)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js:2:26911)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js:2:27724)
    at x (https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js:4:11065)
    at XMLHttpRequest.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js:4:14577)

**Comment by Robotex** [comment]
Browser? Userscript Manager?

**Comment by lordmarte** [comment]
Chrome with violentmonkey

**Comment by Robotex** [comment]
Fixed in v1.3.1
